package cluster

import (
	"errors"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/hesape/database/model"
)

// Cluster is the entity this package owns.
//
// It embeds the model, so a row returned by a query carries the connection and
// can be saved again. Build new rows through Clusters: a struct literal has no
// connection and its write methods return model.ErrUnwired.
type Cluster struct {
	model.Model[Cluster]

	// ID is the identifier. It is generated by the application rather than by
	// the database, because a DEFAULT that produces a uuid is spelled
	// differently in every engine.
	ID string `db:"id"`

	// TenantID is the customer the row belongs to. It is written from the
	// Grant and read back so the policy can compare it against the subject's
	// tenant.
	TenantID string `db:"tenant_id"`

	// Name is what a person calls this record.
	Name string `db:"name"`

	// CreatedAt is when the row was written, in UTC.
	CreatedAt time.Time `db:"created_at"`
}

// Clusters returns the configured model for the clusters table.
//
// The primary key is application-generated text, so it does not increment.
// The tenant scope remains on the model's tenant_id default.
func Clusters(db *data.DB) *model.Model[Cluster] {
	m := model.NewModel[Cluster]("clusters", db, db.GetQueryGrammar(), db.GetPostProcessor())
	m.KeyType = "string"
	m.Incrementing = false
	return m
}

// ErrNotFound is returned when no row matches, including when the row exists
// in another tenant. The two cases are deliberately indistinguishable.
var ErrNotFound = errors.New("cluster: record not found")

// Resource is the list of fields one Cluster is allowed to answer with.
//
// A declared list rather than the entity itself. An encoder handed the entity
// answers with whatever fields it happens to have, including the ones somebody
// adds later without ever opening the handler -- and TenantID is exactly such a
// field: it names another customer's identifier and belongs in no response.
type Resource struct {
	id        string
	name      string
	createdAt time.Time
}

// NewResource snapshots one record for the response.
func NewResource(record Cluster) Resource {
	return newResource(record.ID, record.Name, record.CreatedAt)
}

func resourceFromPointer(record *Cluster) Resource {
	if record == nil {
		return Resource{}
	}
	return newResource(record.ID, record.Name, record.CreatedAt)
}

func newResource(id, name string, createdAt time.Time) Resource {
	return Resource{id: id, name: name, createdAt: createdAt}
}

// ToArray returns the fields that may leave, by name.
func (r Resource) ToArray() map[string]any {
	return map[string]any{
		"id":         r.id,
		"name":       r.name,
		"created_at": r.createdAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields at the top level of the response.
// Nothing does here, and a resource that has nothing to add says so by
// answering nil.
func (r Resource) With() map[string]any { return nil }

// Collection is a page of records as one response.
type Collection struct {
	records []Resource
	// cursor is what the next page asks for, empty when this page is the last
	// one. It goes beside the items rather than inside them: it describes the
	// answer, not the things answered with.
	cursor string
}

// NewCollection wraps a page of records for the response. The cursor is what
// the next request passes back, and is empty when there is no next page.
func NewCollection(records []Cluster, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		resources = append(resources, NewResource(record))
	}
	return Collection{records: resources, cursor: cursor}
}

// collectionFromPointers takes the Model-backed rows returned by a terminal
// and snapshots only what the response reads. The public constructor keeps its
// value-based API for callers that build resources without touching storage.
func collectionFromPointers(records []*Cluster, cursor string) Collection {
	resources := make([]Resource, 0, len(records))
	for _, record := range records {
		if record != nil {
			resources = append(resources, resourceFromPointer(record))
		}
	}
	return Collection{records: resources, cursor: cursor}
}

// ToArray returns the page under a single key, so that the shape of the
// response does not change when a second key is added beside it.
func (c Collection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, record.ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, and nothing when there is none.
func (c Collection) With() map[string]any {
	if c.cursor == "" {
		return nil
	}
	return map[string]any{"next_cursor": c.cursor}
}
